# Generated by Django 3.2.12 on 2022-02-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Signup_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Roll_Number', models.CharField(max_length=6)),
                ('Course', models.CharField(max_length=10)),
                ('Branch', models.CharField(max_length=50)),
            ],
        ),
    ]
