# Generated by Django 3.2.12 on 2022-02-11 15:54

import django.core.validators
from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='student_signup_form',
            name='id',
        ),
        migrations.AddField(
            model_name='student_signup_form',
            name='Gender',
            field=models.CharField(blank=True, choices=[('f', 'Female'), ('m', 'Male'), ('u', 'Undisclosed')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student_signup_form',
            name='School',
            field=models.CharField(blank=True, choices=[('c', 'SCEE'), ('b', 'SBS'), ('e', 'SE'), ('h', 'SHSS')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student_signup_form',
            name='Course',
            field=models.CharField(blank=True, choices=[('b', 'B.Tech'), ('m', 'M.tech/MS'), ('p', 'PhD')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student_signup_form',
            name='Roll_Number',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Prof_Signup_Form',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Email_ID', models.CharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.EmailValidator(message='Please check your email again'), login.models.email_checker])),
                ('Designation', models.CharField(blank=True, choices=[('a', 'Assistant Professor'), ('A', 'Associate Professor'), ('p', 'Professor')], max_length=1, null=True)),
                ('School', models.CharField(blank=True, choices=[('c', 'SCEE'), ('b', 'SBS'), ('e', 'SE'), ('h', 'SHSS')], max_length=1, null=True)),
                ('Course_Offered_1', models.ManyToManyField(to='login.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='student_signup_form',
            name='Subject_1',
            field=models.ManyToManyField(to='login.Subject'),
        ),
    ]
