# Generated by Django 3.2.12 on 2022-02-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20220211_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof_signup_form',
            name='Designation',
            field=models.CharField(choices=[('a', 'Assistant Professor'), ('A', 'Associate Professor'), ('p', 'Professor')], max_length=1),
        ),
        migrations.AlterField(
            model_name='prof_signup_form',
            name='School',
            field=models.CharField(choices=[('c', 'SCEE'), ('b', 'SBS'), ('e', 'SE'), ('h', 'SHSS')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student_signup_form',
            name='Course',
            field=models.CharField(choices=[('b', 'B.Tech'), ('m', 'M.tech/MS'), ('p', 'PhD')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student_signup_form',
            name='Gender',
            field=models.CharField(choices=[('f', 'Female'), ('m', 'Male'), ('u', 'Undisclosed')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student_signup_form',
            name='School',
            field=models.CharField(choices=[('c', 'SCEE'), ('b', 'SBS'), ('e', 'SE'), ('h', 'SHSS')], max_length=1),
        ),
    ]
