# Generated by Django 4.0.2 on 2022-02-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_Img', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_images',
            name='student_Img',
            field=models.ImageField(upload_to='images/<django.db.models.fields.CharField>.jpg'),
        ),
    ]
