# Generated by Django 4.0.2 on 2022-02-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_Img', '0002_alter_student_images_student_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_images',
            name='student_Img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
