# Generated by Django 3.2.12 on 2022-02-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_Img', '0003_alter_student_images_student_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_images',
            old_name='name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='student_images',
            name='student_Img',
        ),
        migrations.AddField(
            model_name='student_images',
            name='Face_Images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
