# Generated by Django 3.2.12 on 2022-02-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_Img', '0004_auto_20220209_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_images',
            old_name='Name',
            new_name='Roll_Number',
        ),
    ]
